# Assignment 5 Basic Wrangling

Do the basic data wrangling that we performed in class on the given data set **fifa.csv**.

- Basic Data Exploration
- Missing Values
- Duplicates
- Selecting / Dropping Columns
- String operations on whole columns
- Column splits/transformations

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('fifa.csv')

# 1. Basic Data Exploration

In [7]:
df.head(5)

,id,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
0,1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.0
1,100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,NaN
2,100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,NaN
3,100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,NaN
4,100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,NaN

** Change index of dataset **

Before changing index verify that the new index column has has no duplicates

In [8]:
df.duplicated(['id']).sum()

0

AS column **_id_** has no duplicates, so we can safely set it as our index.

In [9]:
df.set_index('id',inplace=True)

In [10]:
df.index[df.index.duplicated()].unique()

Int64Index([], dtype='int64', name='id')

In [11]:
df.head(5)

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.0
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,NaN
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,NaN
100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,NaN
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8847 entries, 1001 to 9913
Data columns (total 18 columns):
 name           8847 non-null object
 rating         8847 non-null int64
 position       8847 non-null object
 height         8847 non-null int64
 foot           8847 non-null object
 rare           8847 non-null int64
 pace           8847 non-null object
 shooting       8847 non-null object
 passing        8847 non-null object
 dribbling      8847 non-null object
 defending      8847 non-null object
 heading        8847 non-null object
 diving         8847 non-null object
 handling       8847 non-null object
 kicking        8847 non-null object
 reflexes       8847 non-null object
 speed          8847 non-null object
 positioning    930 non-null float64
dtypes: float64(1), int64(3), object(14)
memory usage: 1.6+ MB

In [13]:
df.columns

Index([' name', ' rating', ' position', ' height', ' foot', ' rare', ' pace',
       ' shooting', ' passing', ' dribbling', ' defending', ' heading',
       ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')

AS we see columns have spaces in the begining, we have to remove these spaces.

In [14]:
columns = list(df.columns)
columns
columns = [x.strip(' ') for x in columns]
df.columns = columns

In [15]:
df.head(5)

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.0
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,NaN
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,NaN
100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,NaN
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,NaN

# 2. Missing Values

In [16]:
df.isnull().sum()

name              0
rating            0
position          0
height            0
foot              0
rare              0
pace              0
shooting          0
passing           0
dribbling         0
defending         0
heading           0
diving            0
handling          0
kicking           0
reflexes          0
speed             0
positioning    7917
dtype: int64

In [17]:
# Replace `NaN` values with the mean of the column
df.fillna(df.mean(), inplace=True)
df.isnull().sum()

name           0
rating         0
position       0
height         0
foot           0
rare           0
pace           0
shooting       0
passing        0
dribbling      0
defending      0
heading        0
diving         0
handling       0
kicking        0
reflexes       0
speed          0
positioning    0
dtype: int64

In [18]:
df.head(10)

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.000000
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,64.955914
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,64.955914
100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,64.955914
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,64.955914
100329,Abdoulaye Faye,72,D,187,Right,1,50,37,47,43,76,82,,,,,,64.955914
100330,José Saez,67,M,170,Right,0,53,60,65,61,64,60,,,,,,64.955914
100391,Laurent Delorge,67,M,179,Right,0,76,58,67,64,63,56,,,,,,64.955914
100521,David Noble,64,M,183,Right,1,62,52,66,65,56,53,,,,,,64.955914
100522,Dominic Foley,62,A,186,Left,1,34,65,55,55,56,77,,,,,,64.955914

# 3. Duplicates

In [19]:
df.name[df.name.duplicated()].unique()

array([' Juanma', ' Damien Perquis', ' Adriano', ' Diego', ' Lúcio',
       ' Kléber', ' David García', ' Ricardo', ' Corona', ' Juanfran',
       ' Cristian', ' Peña', ' Rubén', ' Rodri', ' Luciano', ' Alex',
       ' Maicon', ' Amaya', ' Paul Robinson', ' Roberto', ' Stephen Hunt',
       ' Mauricio Romero', ' Milan Jovanović', ' Souza', ' Sergio',
       ' Eduardo', " James O'Connor", ' Caio', ' Cássio', ' Júlio César',
       ' Anderson', ' Mark Hughes', ' Sastre', ' João Paulo', ' Varela',
       ' Wayne Brown', ' Gonzalo Castro', ' Gilberto', ' Ayoze',
       ' Lee Sang Ho', ' Marcelo', ' Ben Smith', ' Henrique',
       ' Andy Williams', ' Gary Roberts', ' Bruno', ' Rafinha',
       ' Marco Rossi', ' Marcos', ' Nenê', ' Fred', ' Emerson', ' Lima',
       ' Guilherme', ' Jonas', ' Felipe', ' Everton', ' Adi', ' Cris',
       ' William', ' David González', ' Ángel', ' Chris Martin',
       ' Fabiano', ' Charles', ' Tommy Smith', ' Alberto', ' Elias',
       ' Diogo', ' Zé Eduardo', ' Wellington', ' Douglas',
       ' Matthew Taylor', ' Peter Murphy', ' Saúl', ' Ashley Westwood',
       ' Susaeta', ' Fábio', ' Rafael', ' Renan', ' Samuel', ' Oier',
       ' Míchel', ' Bernardo', ' Wesley', ' Cicinho', ' Kike', ' Galán',
       ' André Santos', ' Juan Dominguez', ' Roger', " Mark O'Brien",
       ' Toni', ' Raúl', ' Willian', ' Billy Jones', ' Juninho',
       ' Llorente', ' Rodrigo', ' Fabricio', ' Michel', ' Danilo',
       ' Kanu', ' Josué', ' Paulinho', ' Lucas', ' Diego Jiménez',
       ' Miranda', ' James Henry', ' Juan Carlos', ' Gabriel',
       ' Lee Yong', ' Mike Jones', ' Chris Taylor', ' Adam Smith',
       ' Antonio López', ' Tiago', ' Leonardo', ' Ryan Taylor',
       ' Andreas Johansson', ' Capdevila', ' Gaspar', ' Moreira',
       ' André Luiz', ' Rivaldo', ' Juan', ' Leandro', ' Mark Wilson',
       ' Nano', ' Fernando Navarro', ' Portillo'], dtype=object)

In [20]:
df.duplicated().sum()

0

In [21]:
df[df.duplicated()]

Empty DataFrame
Columns: [name, rating, position, height, foot, rare, pace, shooting, passing, dribbling, defending, heading, diving, handling, kicking, reflexes, speed, positioning]
Index: []

# 4. Selecting / Dropping Columns

In [22]:
df[df.foot == ' Right']

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.000000
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,64.955914
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,64.955914
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,64.955914
100329,Abdoulaye Faye,72,D,187,Right,1,50,37,47,43,76,82,,,,,,64.955914
100330,José Saez,67,M,170,Right,0,53,60,65,61,64,60,,,,,,64.955914
100391,Laurent Delorge,67,M,179,Right,0,76,58,67,64,63,56,,,,,,64.955914
100521,David Noble,64,M,183,Right,1,62,52,66,65,56,53,,,,,,64.955914
100559,Paul McKenna,68,M,170,Right,0,53,65,68,63,70,69,,,,,,64.955914
100574,Paweł Abbott,59,A,187,Right,0,51,60,49,51,54,64,,,,,,64.955914
100578,Richard Cresswell,66,A,183,Right,1,56,63,53,49,62,72,,,,,,64.955914
100580,David Healy,69,A,173,Right,0,64,72,51,60,48,69,,,,,,64.955914
100585,Dickson Etuhu,75,M,188,Right,1,59,55,64,63,80,72,,,,,,64.955914
100670,Ashley Westwood,54,D,183,Right,0,47,26,39,40,62,57,,,,,,64.955914
100701,Paul Ifill,70,A,180,Right,0,72,65,59,78,54,52,,,,,,64.955914
100707,David Artell,59,D,188,Right,0,48,27,38,36,65,68,,,,,,64.955914
100743,Martin Rowlands,64,M,175,Right,1,52,60,66,66,63,59,,,,,,64.955914
100745,Paul Smith,64,GK,193,Right,1,,,,,,,65,62,55,67,41,62.000000
100751,Kevin O'Connor,59,D,180,Right,0,53,48,60,53,62,55,,,,,,64.955914
100792,Brynjar Gunnarsson,61,M,183,Right,0,34,54,61,65,68,66,,,,,,64.955914
100798,James O'Connor,63,M,173,Right,0,61,53,61,60,68,70,,,,,,64.955914
100803,Karl Henry,71,M,185,Right,0,55,57,71,71,73,64,,,,,,64.955914
100807,Stefanos Kotsolis,65,GK,190,Right,0,,,,,,,62,68,62,65,60,64.000000
100889,Louis Carey,67,D,178,Right,0,45,31,45,38,69,78,,,,,,64.955914
100899,Steve Phillips,61,GK,185,Right,1,,,,,,,46,65,76,71,31,61.000000
100907,Danny Coles,62,D,185,Right,0,70,32,33,35,66,67,,,,,,64.955914
100932,Sotirios Kyrgiakos,76,D,193,Right,1,41,42,46,38,80,80,,,,,,64.955914
100954,Monsef Zerka,63,M,183,Right,0,69,60,59,64,53,63,,,,,,64.955914
100964,Romain Poyet,72,A,184,Right,1,68,70,70,73,56,74,,,,,,64.955914
101160,Nicoló Consolini,63,D,180,Right,0,71,47,60,57,63,58,,,,,,64.955914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8473,Tomáš Rosický,81,M,179,Right,1,68,75,81,84,50,52,,,,,,64.955914
8517,Scott Parker,82,M,175,Right,1,73,76,81,76,78,74,,,,,,64.955914
860,Danny Senda,57,D,178,Right,0,70,44,61,59,60,63,,,,,,64.955914
8753,Omar Daf,68,D,177,Right,0,61,38,62,47,72,69,,,,,,64.955914
878,Danny Schofield,64,M,178,Right,0,64,58,62,61,56,59,,,,,,64.955914
8798,Movilla,69,M,171,Right,0,45,57,72,56,66,53,,,,,,64.955914
880,Nat Brown,57,D,188,Right,0,53,32,39,38,62,69,,,,,,64.955914
882,John Thorrington,63,M,173,Right,1,68,64,61,64,62,63,,,,,,64.955914
8830,Giuseppe Colucci,72,M,179,Right,1,57,69,74,69,66,53,,,,,,64.955914
8842,Lionel Scaloni,68,D,182,Right,0,52,65,71,68,70,60,,,,,,64.955914
885,Dwayne Mattis,64,M,183,Right,0,72,47,57,53,68,58,,,,,,64.955914
887,Nathan Clarke,62,D,185,Right,0,56,26,40,35,67,64,,,,,,64.955914
889,Jody Morris,66,M,165,Right,0,64,50,62,73,60,58,,,,,,64.955914
8910,Carlo Nash,63,GK,182,Right,1,,,,,,,60,66,60,63,45,64.000000
899,Frank Rost,74,GK,194,Right,1,,,,,,,72,74,70,75,32,80.000000
9037,Rufete,67,M,176,Right,0,58,64,72,71,59,48,,,,,,64.955914
9195,Pantelis Kafes,70,M,180,Right,1,66,72,73,74,68,63,,,,,,64.955914
9232,Tomasz Frankowski,68,A,172,Right,0,59,67,48,60,42,66,,,,,,64.955914
9273,Thorstein Helstad,70,A,187,Right,1,53,72,61,69,58,73,,,,,,64.955914
9432,Yossi Benayoun,82,M,178,Right,0,71,73,76,82,55,60,,,,,,64.955914
9639,Aitor Ocio,72,D,187,Right,0,32,47,64,56,73,62,,,,,,64.955914
9676,Samuel Eto'o,88,A,180,Right,1,93,83,68,85,58,79,,,,,,64.955914
9722,Nicolai Stokholm,67,M,182,Right,0,59,67,71,56,70,70,,,,,,64.955914
9723,Camel Meriem,71,M,174,Right,0,58,65,69,75,45,62,,,,,,64.955914
9751,Gábor Babos,71,GK,196,Right,1,,,,,,,70,70,60,70,29,75.000000
9799,Pierre-Alain Frau,73,A,175,Right,1,79,72,68,71,54,68,,,,,,64.955914
9805,Craig Bellamy,79,A,175,Right,0,80,78,67,81,62,71,,,,,,64.955914
9807,Michel Breuer,68,D,183,Right,0,61,40,56,51,70,74,,,,,,64.955914
9815,Gill Swerts,65,D,179,Right,0,65,48,63,65,67,69,,,,,,64.955914
9913,Mehdi Nafti,69,M,179,Right,0,55,56,64,65,69,60,,,,,,64.955914

In [23]:
df[df.height >= 150]

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,Gábor Király,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.000000
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,64.955914
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,64.955914
100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,64.955914
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,64.955914
100329,Abdoulaye Faye,72,D,187,Right,1,50,37,47,43,76,82,,,,,,64.955914
100330,José Saez,67,M,170,Right,0,53,60,65,61,64,60,,,,,,64.955914
100391,Laurent Delorge,67,M,179,Right,0,76,58,67,64,63,56,,,,,,64.955914
100521,David Noble,64,M,183,Right,1,62,52,66,65,56,53,,,,,,64.955914
100522,Dominic Foley,62,A,186,Left,1,34,65,55,55,56,77,,,,,,64.955914
100557,Brian Barry-Murphy,60,M,185,Left,0,61,54,60,47,60,48,,,,,,64.955914
100559,Paul McKenna,68,M,170,Right,0,53,65,68,63,70,69,,,,,,64.955914
100574,Paweł Abbott,59,A,187,Right,0,51,60,49,51,54,64,,,,,,64.955914
100578,Richard Cresswell,66,A,183,Right,1,56,63,53,49,62,72,,,,,,64.955914
100580,David Healy,69,A,173,Right,0,64,72,51,60,48,69,,,,,,64.955914
100585,Dickson Etuhu,75,M,188,Right,1,59,55,64,63,80,72,,,,,,64.955914
100670,Ashley Westwood,54,D,183,Right,0,47,26,39,40,62,57,,,,,,64.955914
100701,Paul Ifill,70,A,180,Right,0,72,65,59,78,54,52,,,,,,64.955914
100707,David Artell,59,D,188,Right,0,48,27,38,36,65,68,,,,,,64.955914
100743,Martin Rowlands,64,M,175,Right,1,52,60,66,66,63,59,,,,,,64.955914
100745,Paul Smith,64,GK,193,Right,1,,,,,,,65,62,55,67,41,62.000000
100751,Kevin O'Connor,59,D,180,Right,0,53,48,60,53,62,55,,,,,,64.955914
100756,Stephen Hunt,56,D,185,Left,0,67,32,46,46,59,63,,,,,,64.955914
100758,Jay Tabb,63,M,170,Left,1,69,58,66,65,59,66,,,,,,64.955914
100792,Brynjar Gunnarsson,61,M,183,Right,0,34,54,61,65,68,66,,,,,,64.955914
100798,James O'Connor,63,M,173,Right,0,61,53,61,60,68,70,,,,,,64.955914
100803,Karl Henry,71,M,185,Right,0,55,57,71,71,73,64,,,,,,64.955914
100804,Gareth Owen,62,D,185,Left,0,61,19,48,46,65,67,,,,,,64.955914
100806,Kris Commons,75,M,168,Left,0,79,74,73,80,48,60,,,,,,64.955914
100807,Stefanos Kotsolis,65,GK,190,Right,0,,,,,,,62,68,62,65,60,64.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8753,Omar Daf,68,D,177,Right,0,61,38,62,47,72,69,,,,,,64.955914
878,Danny Schofield,64,M,178,Right,0,64,58,62,61,56,59,,,,,,64.955914
8798,Movilla,69,M,171,Right,0,45,57,72,56,66,53,,,,,,64.955914
880,Nat Brown,57,D,188,Right,0,53,32,39,38,62,69,,,,,,64.955914
882,John Thorrington,63,M,173,Right,1,68,64,61,64,62,63,,,,,,64.955914
8830,Giuseppe Colucci,72,M,179,Right,1,57,69,74,69,66,53,,,,,,64.955914
8842,Lionel Scaloni,68,D,182,Right,0,52,65,71,68,70,60,,,,,,64.955914
885,Dwayne Mattis,64,M,183,Right,0,72,47,57,53,68,58,,,,,,64.955914
887,Nathan Clarke,62,D,185,Right,0,56,26,40,35,67,64,,,,,,64.955914
889,Jody Morris,66,M,165,Right,0,64,50,62,73,60,58,,,,,,64.955914
8910,Carlo Nash,63,GK,182,Right,1,,,,,,,60,66,60,63,45,64.000000
899,Frank Rost,74,GK,194,Right,1,,,,,,,72,74,70,75,32,80.000000
9014,Arjen Robben,90,M,181,Left,1,93,85,81,93,53,60,,,,,,64.955914
9037,Rufete,67,M,176,Right,0,58,64,72,71,59,48,,,,,,64.955914
9195,Pantelis Kafes,70,M,180,Right,1,66,72,73,74,68,63,,,,,,64.955914
9232,Tomasz Frankowski,68,A,172,Right,0,59,67,48,60,42,66,,,,,,64.955914
9273,Thorstein Helstad,70,A,187,Right,1,53,72,61,69,58,73,,,,,,64.955914
9432,Yossi Benayoun,82,M,178,Right,0,71,73,76,82,55,60,,,,,,64.955914
9639,Aitor Ocio,72,D,187,Right,0,32,47,64,56,73,62,,,,,,64.955914
9676,Samuel Eto'o,88,A,180,Right,1,93,83,68,85,58,79,,,,,,64.955914
9722,Nicolai Stokholm,67,M,182,Right,0,59,67,71,56,70,70,,,,,,64.955914
9723,Camel Meriem,71,M,174,Right,0,58,65,69,75,45,62,,,,,,64.955914
9751,Gábor Babos,71,GK,196,Right,1,,,,,,,70,70,60,70,29,75.000000
9771,Orlando Engelaar,73,M,196,Left,1,38,71,71,65,75,61,,,,,,64.955914
9799,Pierre-Alain Frau,73,A,175,Right,1,79,72,68,71,54,68,,,,,,64.955914
9801,Danijel Ljuboja,73,A,189,Left,1,62,73,64,74,56,68,,,,,,64.955914
9805,Craig Bellamy,79,A,175,Right,0,80,78,67,81,62,71,,,,,,64.955914
9807,Michel Breuer,68,D,183,Right,0,61,40,56,51,70,74,,,,,,64.955914
9815,Gill Swerts,65,D,179,Right,0,65,48,63,65,67,69,,,,,,64.955914
9913,Mehdi Nafti,69,M,179,Right,0,55,56,64,65,69,60,,,,,,64.955914

# 5. String operations on whole columns

In [24]:
df.foot.unique()

array([' Right', ' Left'], dtype=object)

In [25]:
df.foot = df.foot.str.replace(' Right', 'Right')
df.foot = df.foot.str.replace(' Left', 'Left')
df.foot.unique()

array(['Right', 'Left'], dtype=object)

In [26]:
df.position.unique()

array([' GK', ' M', ' A', ' D'], dtype=object)

In [27]:
df.position = [x.strip(' ') for x in df.position]

df.position.unique()

array(['GK', 'M', 'A', 'D'], dtype=object)

In [28]:
df.name.unique()

array([' Gábor Király', ' Frederik Boi', ' Tomasz Szewczuk', ...,
       ' Michel Breuer', ' Gill Swerts', ' Mehdi Nafti'], dtype=object)

In [29]:
df.name = [x.strip(' ') for x in df.name]

df.name.unique()

array(['Gábor Király', 'Frederik Boi', 'Tomasz Szewczuk', ...,
       'Michel Breuer', 'Gill Swerts', 'Mehdi Nafti'], dtype=object)

# 6. Column splits/transformations

In [4]:
df.rating.unique()

NameError: name 'df' is not defined

In [136]:
new = df.groupby(['name', 'position'])['rating'].mean().reset_index()
new.sort_values(['name', 'position'], ascending=[True, False], inplace=True)
new

                        name position  rating
0             A.J. DeLaGarza        D    66.0
1                A.J. Soares        D    62.0
2                      Aaron        A    66.0
3                Aaron Brown        D    55.0
4            Aaron Cresswell        D    64.0
5                Aaron Doran        M    65.0
6                Aaron Forde        M    45.0
7               Aaron Greene        A    58.0
8               Aaron Hughes        D    76.0
9                 Aaron Hunt        M    75.0
10              Aaron Lennon        M    82.0
11              Aaron Martin        D    64.0
12             Aaron McCarey       GK    59.0
13              Aaron McLean        A    66.0
14             Aaron Mokoena        M    70.0
15                Aaron Mooy        M    61.0
16              Aaron Ramsey        M    77.0
17           Aaron Wilbraham        A    61.0
18             Aarón Galindo        D    69.0
19             Aarón Padilla        A    61.0
20         Aatif Chahechouhe        M    56.0
21    Abdelhamid El Kaoutari        D    72.0
22        Abdelkader Ghezzal        A    73.0
23         Abderrazzak Jadid        M    66.0
24         Abdisalam Ibrahim        M    65.0
25       Abdou Razack Traoré        A    75.0
26              Abdou Traoré        M    67.0
27         Abdoul Karim Yoda        M    66.0
28    Abdoul Razzagui Camara        A    69.0
29            Abdoulay Konko        D    76.0
...                      ...      ...     ...
8764                 Éverton        M    69.0
8765                   Índio        M    68.0
8766        Ívar Ingimarsson        D    67.0
8767             Íñigo Vélez        A    63.0
8768         Ólafur Skúlason        M    63.0
8769                   Óscar        M    71.0
8770           Óscar Cardozo        A    81.0
8771             Óscar Pérez       GK    68.0
8772             Óscar Rojas        D    69.0
8773           Óscar Sánchez        D    61.0
8774             Óscar Trejo        A    74.0
8775             Ömer Bayram        A    59.0
8776             Ömer Toprak        D    74.0
8777          Özkan Yildirim        M    62.0
8778         Øyvind Storflor        A    66.0
8779            Ümit Korkmaz        M    71.0
8780          Łukasz Burliga        D    59.0
8781        Łukasz Fabiański       GK    77.0
8782          Łukasz Garguła        M    68.0
8783           Łukasz Hanzel        M    59.0
8784         Łukasz Janoszka        M    58.0
8785            Łukasz Madej        M    64.0
8786         Łukasz Piszczek        D    76.0
8787           Łukasz Sapela       GK    63.0
8788            Łukasz Surma        M    60.0
8789           Łukasz Trałka        M    67.0
8790         Łukasz Tymiński        M    54.0
8791          Łukasz Załuska       GK    69.0
8792               Šaćir Hot        D    57.0
8793         Žarco Tomašević        D    68.0

[8794 rows x 3 columns]

NameError: name 'df' is not defined

In [30]:
#Group By Location and Time
df_loc_time = df.groupby(['Location Category', 'Time'])['Killed', 'Injured'].sum()
#Reset Index
df_loc_time.reset_index(level=[0, 1], inplace=True)

KeyError: 'Location Category'